routes/web.php
<?php

use App\Models\Category;
use App\Models\Publication;
use Illuminate\Routing\Router;

/** @var Router $route */
/** @noinspection PhpUnhandledExceptionInspection */
$route = app()->make('router');

$route->bind('category', function($value){
    return Category::query()->where('slug', $value)->first();
});

$route->bind('publication', function($value) {
    return Publication::query()->where('slug', $value)->first();
});

/**
 * Auth only routes
 */
$route->group(['middleware' => ['auth']], function(Router $route) {

    $route->group(['as' => 'auth.', 'prefix' => 'auth'], function(Router $route) {
        $route->get('logout', 'AuthController@logout')->name('logout');
    });

    $route->resource('address', 'AddressController')->except(['show']);

    $route->group(['as' => 'publication.', 'prefix' => 'publication'], function(Router $route) {
        $route->get('create', 'PublicationController@create')->name('create');
        $route->post('/', 'PublicationController@store')->name('store');
    });

});

/**
 * Guest only routes
 */
$route->group(['middleware' => ['guest']], function(Router $route) {

    $route->group(['as' => 'auth.', 'prefix' => 'auth'], function(Router $route){
        $route->get('login', 'AuthController@login')->name('login');
        $route->post('login', 'AuthController@doLogin')->name('do-login');

        $route->get('register', 'AuthController@register')->name('register');
        $route->post('register', 'AuthController@doRegister')->name('do-register');
    });

});

/**
 * Public Routes
 */
$route->get('/', 'HomeController@index')->name('home.index');

$route->group(['as' => 'category.', 'prefix' => 'category'], function(Router $route) {
    $route->get('/', 'CategoryController@index')->name('index');
    $route->get('{category}', 'CategoryController@show')->name('show');
});

$route->group(['as' => 'publication.', 'prefix' => 'publication'], function(Router $route) {
    $route->get('/', 'PublicationController@index')->name('index');
    $route->get('{publication}', 'PublicationController@show')->name('show');
    $route->get('{publication}/expertise', 'PublicationController@expertise')->name('expertise');
});

app/Models/Publication.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Publication extends Model implements HasMedia
{
    use InteractsWithMedia;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public $fillable = [
        'name', 'slug', 'content', 'tech', 'age', 'brand', 'model', 'made_in',
    ];

    /**
     * Retrieve category of the publication
     *
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Retrieve seller of the publication
     *
     * @return BelongsTo
     */
    public function seller(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * Retrieve address of the publication
     *
     * @return BelongsTo
     */
    public function address(): BelongsTo
    {
        return $this->belongsTo(Address::class);
    }

    /**
     * Retrieve description of the publication
     *
     * @return string
     */
    public function getDescriptionAttribute(): string
    {
        return Str::limit(strip_tags($this->content), 50);
    }

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('images');
        $this->addMediaCollection('expertise')
              ->singleFile();
    }
}

app/Http/Controllers/PublicationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PublicationCreateRequest;
use App\Models\Publication;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Str;

class PublicationController extends Controller
{
    public function index()
    {
        $publications = Publication::query()->latest()->paginate(20);

        return view('publication.index', [
            'publications' => $publications,
        ]);
    }

    public function show(Publication $publication)
    {
        return view('publication.show', [
            'publication' => $publication,
            'category' => $publication->category,
        ]);
    }

    public function create()
    {
        return view('publication.create');
    }

    public function store(PublicationCreateRequest $request)
    {
        $publication = new Publication($request->only(
            "name", "content", "tech", "brand", "model", "age", "made_in"
        ));

        $publication->slug = Str::slug($request->get('name'));
        $publication->category()->associate($request->get('category_id'));
        $publication->address()->associate($request->get('address_id'));
        $publication->seller()->associate(auth()->user()->id);

        $publication->save();

        foreach ($request->file('images') as $image)
            $publication->addMedia($image)->toMediaCollection('images');
        $publication->addMedia($request->file('expertise'))->toMediaCollection('expertise');

        return redirect()->route('publication.show', $publication->slug);
    }

    public function expertise(Publication $publication)
    {
        return response()->download($publication->getFirstMediaPath('expertise'));
    }
}

resources/views/publication/create.blade.php
@extends('layout.page')

@section('page')
    <main role="main" class="container mb-5 mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header bg-success text-white text-center">
                        Yeni İlan Ekle
                    </div>
                    <div class="card-body">
                        @if ($errors->count())
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                    <p class="mb-0">{{ $error }}</p>
                                @endforeach
                            </div>
                        @endif
                        <form method="post" action="{{ route('publication.store') }}" enctype="multipart/form-data">
                            {!! csrf_field() !!}
                            <div class="form-group">
                                <label for="name">İlan Başlığı</label>
                                <input type="text" name="name" id="name" value="{{ old('name') }}" placeholder="İlan Başlığı" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="category_id">Kategori</label>
                                <select id="category_id" name="category_id" class="form-control">
                                    @foreach (\App\Models\Category::all() as $item)
                                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="address_id">Adres</label>
                                <select id="address_id" name="address_id" class="form-control">
                                    @foreach (auth()->user()->addresses as $item)
                                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="content">İlan İçeriği</label>
                                <textarea name="content" id="content" class="form-control editor" rows="5" placeholder="İlan içeriğini giriniz..."></textarea>
                            </div>
                            <div class="form-group">
                                <label for="content">Teknik Detaylar</label>
                                <textarea name="tech" id="tech" class="form-control editor" rows="5" placeholder="İlan teknik detayları giriniz..."></textarea>
                            </div>
                            <div class="form-group">
                                <label for="images">Fotoğraflar</label>
                                <input type="file" name="images[]" id="images" multiple class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="brand">İlan Marka / Model</label>
                                <div class="row">
                                    <div class="col-md-6">
                                        <input type="text" name="brand" id="brand" value="{{ old('brand') }}" placeholder="Marka" class="form-control">
                                    </div>
                                    <div class="col-md-6">
                                        <input type="text" name="model" id="model" value="{{ old('model') }}" placeholder="Model" class="form-control">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="age">Araç Yaşı</label>
                                <input type="number" name="age" id="age" min="1" value="{{ old('age') ?: 1 }}" placeholder="Aracın Yaşı" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="made_in">Üretildiği Yer</label>
                                <input type="text" name="made_in" id="made_in" value="{{ old('made_in') }}" placeholder="Aracın Üretildiği Yer" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="expertise">Expertiz Raporu</label>
                                <input type="file" name="expertise" id="expertise" class="form-control">
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-success">İlanı Yayınla</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

resources/views/publication/index.blade.php
@extends('layout.page')

@section('page')
    <main role="main" class="container">
        @include('partial.publications', ['publications' => $publications])
    </main>
@endsection

resources/views/publication/show.blade.php
@extends('layout.page')

@section('page')
    <main role="main" class="container mb-4">
        <div class="row">
            <div class="col-md-4">
                <div class="card text-center">
                    <div class="card-header">
                        Fotoğraflar
                    </div>
                    <div class="card-body p-0">
                        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                @foreach ($publication->getMedia('images') as $image)
                                <li data-target="#carouselExampleIndicators" data-slide-to="{{ $loop->index }}" @if($loop->first) class="active" @endif></li>
                                @endforeach
                            </ol>
                            <div class="carousel-inner">
                                @foreach ($publication->getMedia('images') as $image)
                                <div class="carousel-item @if($loop->first) active @endif">
                                    <img src="{{ asset($image->getFullUrl()) }}" class="d-block w-100" alt="">
                                </div>
                                @endforeach
                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="card text-center">
                    <div class="card-header bg-primary text-white">
                        {{ $publication->name }}
                    </div>
                    <div class="card-body">
                        {!! $publication->content !!}
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card text-center">
                    <div class="card-header bg-success text-white">
                        {{ $publication->seller->name }}
                    </div>
                    <div class="card-body">
                        <p>
                            <img src="https://www.gravatar.com/avatar/{{ md5($publication->seller->email) }}.png" class="img-thumbnail rounded-circle" />
                        </p>
                        <p>Üyelik tarihi: {{ $publication->seller->created_at->format("d.m.Y") }}</p>
                        <p class="m-0">İlan Sayısı: {{ $publication->seller->publications()->count() }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12">
                <ul class="nav nav-tabs" id="tabs" role="tablist">
                    <li class="nav-item" role="presentation">
                        <a class="nav-link active" id="tech-tab" data-toggle="tab" href="#tech" role="tab" aria-controls="tech" aria-selected="true">Teknik Özellikler</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="expertise-tab" data-toggle="tab" href="#expertise" role="tab" aria-controls="expertise" aria-selected="false">Expertiz Raporu</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="location-tab" data-toggle="tab" href="#location" role="tab" aria-controls="location" aria-selected="false">Lokasyon</a>
                    </li>
                </ul>
                <div class="tab-content" id="tabContents">
                    <div class="tab-pane fade show active p-4" style="border: 1px solid #dee2e6; border-top: 0;" id="tech" role="tabpanel" aria-labelledby="tech-tab">
                        {!! $publication->tech !!}
                    </div>
                    <div class="tab-pane fade p-4" style="border: 1px solid #dee2e6; border-top: 0;" id="expertise" role="tabpanel" aria-labelledby="expertise-tab">
                        <a href="{{ route('publication.expertise', $publication->slug) }}" class="btn btn-primary">Expertiz Raporunu İndir</a>
                    </div>
                    <div class="tab-pane fade p-4" style="border: 1px solid #dee2e6; border-top: 0;" id="location" role="tabpanel" aria-labelledby="location-tab">
                        <p>{{ $publication->address->address }}</p>
                        <iframe
                            style="width: 100%; height: 450px; border: 0;"
                            frameborder="0"
                            src="https://www.google.com/maps/embed/v1/place?key={{ config('services.google_maps.api') }}&q={{ $publication->address->latitude }},{{ $publication->address->longitude }}" allowfullscreen>
                        </iframe>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection