routes/web.php
<?php

use App\Models\Category;
use App\Models\Publication;
use Illuminate\Routing\Router;

/** @var Router $route */
/** @noinspection PhpUnhandledExceptionInspection */
$route = app()->make('router');

$route->bind('category', function($value){
    return Category::query()->where('slug', $value)->first();
});

$route->bind('publication', function($value) {
    return Publication::query()->where('slug', $value)->first();
});

/**
 * Auth only routes
 */
$route->group(['middleware' => ['auth']], function(Router $route) {

    $route->group(['as' => 'auth.', 'prefix' => 'auth'], function(Router $route) {
        $route->get('logout', 'AuthController@logout')->name('logout');
    });

    $route->resource('address', 'AddressController')->except(['show']);

    $route->group(['as' => 'publication.', 'prefix' => 'publication'], function(Router $route) {
        $route->get('create', 'PublicationController@create')->name('create');
        $route->post('/', 'PublicationController@store')->name('store');
    });

});

/**
 * Guest only routes
 */
$route->group(['middleware' => ['guest']], function(Router $route) {

    $route->group(['as' => 'auth.', 'prefix' => 'auth'], function(Router $route){
        $route->get('login', 'AuthController@login')->name('login');
        $route->post('login', 'AuthController@doLogin')->name('do-login');

        $route->get('register', 'AuthController@register')->name('register');
        $route->post('register', 'AuthController@doRegister')->name('do-register');
    });

});

/**
 * Public Routes
 */
$route->get('/', 'HomeController@index')->name('home.index');

$route->group(['as' => 'category.', 'prefix' => 'category'], function(Router $route) {
    $route->get('/', 'CategoryController@index')->name('index');
    $route->get('{category}', 'CategoryController@show')->name('show');
});

$route->group(['as' => 'publication.', 'prefix' => 'publication'], function(Router $route) {
    $route->get('/', 'PublicationController@index')->name('index');
    $route->get('{publication}', 'PublicationController@show')->name('show');
    $route->get('{publication}/expertise', 'PublicationController@expertise')->name('expertise');
});

app/Http/Controllers/AddressController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AddressCreateRequest;
use App\Http\Requests\AddressEditRequest;
use App\Models\Address;
use App\Models\User;

class AddressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        /** @var User $user */
        $user = auth()->user();
        $addresses = $user->addresses()->latest()->paginate(20);

        return view('address.index', [
            'addresses' => $addresses,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('address.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param AddressCreateRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddressCreateRequest $request)
    {
        $address = new Address($request->only('name', 'address', 'latitude', 'longitude'));
        $address->user()->associate(auth()->user());
        $address->save();

        return redirect()->route('address.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Address $address
     * @return \Illuminate\Http\Response
     */
    public function edit(Address $address)
    {
        return view('address.edit', [
            'address' => $address,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param AddressEditRequest $request
     * @param Address $address
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(AddressEditRequest $request, Address $address)
    {
        $address->update($request->only('name', 'address', 'latitude', 'longitude'));

        return redirect()->route('address.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Address $address
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Address $address)
    {
        $address->delete();

        return redirect()->route('address.index');
    }
}

resources/views/address/create.blade.php
@extends('layout.page')

@push('script.page')
    <script>
        $('#location-picker').locationpicker();
    </script>
@endpush

@section('page')
    <main role="main" class="container mb-5 mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header bg-success text-white text-center">
                        Yeni Adres Ekle
                    </div>
                    <div class="card-body">
                        @if ($errors->count())
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                    <p class="mb-0">{{ $error }}</p>
                                @endforeach
                            </div>
                        @endif
                        <form method="post" action="{{ route('address.store') }}">
                            {!! csrf_field() !!}
                            <div class="form-group">
                                <label for="name">Adres Başlığı</label>
                                <input type="text" name="name" id="name" value="{{ old('name') }}" placeholder="Adres Başlığı" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="address">Adres</label>
                                <textarea name="address" id="address" class="form-control" rows="5" placeholder="Adres metnini giriniz...">{{ old('address') }}</textarea>
                            </div>
                            <!--
                            <div id="location-picker" style="width: 500px; height: 400px;"></div>
                            -->
                            <div class="text-center">
                                <button type="submit" class="btn btn-success">Adresi Ekle</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

resources/views/address/edit.blade.php
@extends('layout.page')

@section('page')
    <main role="main" class="container mb-5 mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header bg-primary text-white text-center">
                        '{{ $address->name }}' Adresini Güncelle
                    </div>
                    <div class="card-body">
                        @if ($errors->count())
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                    <p class="mb-0">{{ $error }}</p>
                                @endforeach
                            </div>
                        @endif
                        <form method="post" action="{{ route('address.update', $address->id) }}">
                            <input type="hidden" name="_method" value="PUT" />
                            {!! csrf_field() !!}
                            <div class="form-group">
                                <label for="name">Adres Başlığı</label>
                                <input type="text" name="name" id="name" value="{{ old('name') ?: $address->name }}" placeholder="Adres Başlığı" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="address">Adres</label>
                                <textarea name="address" id="address" class="form-control" rows="5" placeholder="Adres metnini giriniz...">{{ old('address') ?: $address->address }}</textarea>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Adresi Güncelle</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection

resources/views/address/index.blade.php
@extends('layout.page')

@section('page')
    <main role="main" class="container mb-5 mt-5">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <p class="text-right">
                    <a href="{{ route('address.create') }}" class="btn btn-success">Yeni Adres Ekle</a>
                </p>
                <div class="card">
                    <div class="card-header bg-primary text-white text-center">
                        Adreslerim
                    </div>
                    <div class="card-body">
                        @if ($addresses->count() > 0)
                            <table class="table table-hover table-striped table-bordered mb-0">
                                <thead>
                                <tr>
                                    <th>Başlık</th>
                                    <th>Adres</th>
                                    <th>İşlemler</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($addresses as $address)
                                    <tr>
                                        <td>{{ $address->name }}</td>
                                        <td>{{ $address->address }}</td>
                                        <td>
                                            <a href="{{ route('address.edit', ['address' => $address->id]) }}" class="btn btn-sm btn-warning">Düzenle</a>
                                            <form style="display: inline-block;" action="{{ route('address.destroy', ['address' => $address->id]) }}" method="POST">
                                                <input type="hidden" name="_method" value="DELETE" />
                                                {!! csrf_field() !!}
                                                <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Silmek istediğinizden emin misiniz?');">Sil</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                            {!! $addresses->links() !!}
                        @else
                            <div class="alert alert-warning mb-0">
                                <p class="m-0">Henüz adres eklemediniz!</p>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection