routes/web.php
<?php

use App\Models\Category;
use App\Models\Publication;
use Illuminate\Routing\Router;

/** @var Router $route */
/** @noinspection PhpUnhandledExceptionInspection */
$route = app()->make('router');

$route->bind('category', function($value){
    return Category::query()->where('slug', $value)->first();
});

$route->bind('publication', function($value) {
    return Publication::query()->where('slug', $value)->first();
});

/**
 * Auth only routes
 */
$route->group(['middleware' => ['auth']], function(Router $route) {

    $route->group(['as' => 'auth.', 'prefix' => 'auth'], function(Router $route) {
        $route->get('logout', 'AuthController@logout')->name('logout');
    });

    $route->resource('address', 'AddressController')->except(['show']);

    $route->group(['as' => 'publication.', 'prefix' => 'publication'], function(Router $route) {
        $route->get('create', 'PublicationController@create')->name('create');
        $route->post('/', 'PublicationController@store')->name('store');
    });

});

/**
 * Guest only routes
 */
$route->group(['middleware' => ['guest']], function(Router $route) {

    $route->group(['as' => 'auth.', 'prefix' => 'auth'], function(Router $route){
        $route->get('login', 'AuthController@login')->name('login');
        $route->post('login', 'AuthController@doLogin')->name('do-login');

        $route->get('register', 'AuthController@register')->name('register');
        $route->post('register', 'AuthController@doRegister')->name('do-register');
    });

});

/**
 * Public Routes
 */
$route->get('/', 'HomeController@index')->name('home.index');

$route->group(['as' => 'category.', 'prefix' => 'category'], function(Router $route) {
    $route->get('/', 'CategoryController@index')->name('index');
    $route->get('{category}', 'CategoryController@show')->name('show');
});

$route->group(['as' => 'publication.', 'prefix' => 'publication'], function(Router $route) {
    $route->get('/', 'PublicationController@index')->name('index');
    $route->get('{publication}', 'PublicationController@show')->name('show');
    $route->get('{publication}/expertise', 'PublicationController@expertise')->name('expertise');
});

resources/views/partial/footer.blade.php
<footer class="app-footer">
    <p>Bu proje Mersin Üniversitesi İnternet Programlama Final ödevi için <a href="https://era.yayd.in">Eray Aydın</a> tarafından hazırlanmıştır.</p>
    <p>
        <a href="#">Yukarıya Dön</a>
    </p>
</footer>

resources/views/partial/header.blade.php
<header class="app-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
            <a class="btn btn-sm btn-secondary" href="{{ route('publication.index') }}">İlanlar</a>
            <a class="btn btn-sm btn-success" href="{{ route('publication.create') }}">İlan Ekle</a>
        </div>
        <div class="col-4 text-center">
            <a class="app-header-logo text-dark" href="{{ route('home.index') }}">{{ config('app.name') }}</a>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#" aria-label="Search">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Arama</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
            </a>
            @if(auth()->check())
                <a class="btn btn-sm btn-success" href="{{ route('address.index') }}">Adreslerim</a> &nbsp;
                <a class="btn btn-sm btn-primary" href="#">Hesabım</a> &nbsp;
                <a class="btn btn-sm btn-danger" href="{{ route('auth.logout') }}">Çıkış Yap</a>
            @else
                <a class="btn btn-sm btn-primary" href="{{ route('auth.login') }}">Giriş Yap</a> &nbsp;
                <a class="btn btn-sm btn-success" href="{{ route('auth.register') }}">Kayıt Ol</a>
            @endif
        </div>
    </div>
</header>

resources/views/partial/nav.blade.php
<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
        @foreach (\App\Models\Category::all() as $nav)
            <a class="nav-link p-2 @if(isset($category) && $category->id == $nav->id) text-primary @else text-muted @endif" href="{{ route('category.show', $nav->slug) }}">{{ $nav->name }}</a>
        @endforeach
    </nav>
</div>

resources/views/partial/publications.blade.php
@if($publications->count() > 0)
    @foreach ($publications->chunk(4) as $chunk)
        <div class="row">
            @foreach ($chunk as $publication)
                <div class="col-md-3">
                    <div class="no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                        <div>
                            <img src="http://placehold.it/800x600" style="width: 100%" />
                        </div>
                        <div class="p-4 d-flex flex-column position-static">
                            <p class="m-0">
                                <strong class="d-inline-block mb-2 text-primary">{{ $publication->category->name }}</strong>
                                <strong class="d-inline-block mb-2 text-success float-right">{{ $publication->seller->name }}</strong>
                            </p>
                            <h3 class="mb-0">{{ $publication->name }}</h3>
                            <div class="mb-1 text-muted">{{ $publication->created_at->locale('tr')->diffForHumans() }}</div>
                            <p class="card-text mb-auto">{{ $publication->description }}</p>
                            <a href="{{ route('publication.show', $publication->slug) }}" class="stretched-link btn btn-primary mt-3">Detaylar</a>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    @endforeach

    @if (isset($paginated) && $paginated)
        {!! $publications->links() !!}
    @endif
@else
    <div class="alert alert-danger">
        <h3>İlan bulunamadı!</h3>
    </div>
@endif